<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<link rel="stylesheet" href="<?=FILE_URL?>/css/css.css" type="text/css">
<META http-equiv=Content-Type content="text/html; charset=utf-8">
<BODY bgColor=#d6dff7 leftMargin=0 topMargin=0 marginwidth="0" marginheight="0">
<TABLE cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
  <TBODY>
  <TR>
    <TD class=txlHeaderBackgroundAlternate id=TableTitleLink vAlign=center 
    width="43%" height=23>&nbsp;&nbsp; → 欢迎你 < <?=$this->acl?> > [ <b><?=$this->admin_info['user_name']?></b> ],进入 <b>【御承堂】</b> 管理平台 

	<A HREF='?logout=1' target=_top><font color=blue><b>退出</font></A>
	</TD>
    <TD class=txlHeaderBackgroundAlternate id=TableTitleLink vAlign=center 
    width="21%">&nbsp;</TD>
    <TD class=txlHeaderBackgroundAlternate id=TableTitleLink vAlign=center 
    align=right width="36%">
	&nbsp;&nbsp;</TD>
  </TR></TBODY></TABLE></BODY></HTML>
