<!DOCTYPE html>
<html>
 <head>
  <title>管理员后台</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
 </head>

<frameset name=frameMain id=frameMain rows="20,*" cols="*" frameborder="no" border="0" framespacing="0">
  <frame src="/admin-index-head.html" name="top" scrolling="No" noresize="noresize" id="top" title="top" />
  <frameset name=editMain id=editMain cols="202,*" frameborder="yes" border="0" framespacing="0">
    <frame src="/admin-index-left.html" name="left" scrolling="yes" id="left" title="left" />
    <frame src="/admin-index-main.html" name="main" id="main" title="main" />
  </frameset>
</frameset>

<noframes><body>
</body>
</noframes>

</html>

