<div class="ftzw"></div>
<nav class="menubar">
	<a class="menu<?php if($this->action=='index') echo ' sel';?>" data-role="tab" href="/index.html?for_wx_s_bug5" data-toggle="article">
		<span class="menu-icon iconfont i-md1">御承堂</span>
	</a>
	<a class="menu" data-role="tab" href="http://www.yuchengtang.com.cn/reservation" data-toggle="article">
		<span class="menu-icon iconfont i-md-reservation">预约观展</span>
	</a>
	<a class="menu<?php if($this->action=='d' || $this->action=='m' || ($this->action=='l' && $this->type!='z')) echo ' sel';?>" data-role="tab" href="/v-m.html?for_wx_s_bug3" data-toggle="article">
		<span class="menu-icon iconfont i-md3">馆藏展品</span>
	</a>
	<!-- <a class="menu<?php if($this->action=='b' || $this->action=='a') echo ' sel';?>" data-role="tab" href="/v-a.html?for_wx_s_bug4" data-toggle="article">
		<span class="menu-icon iconfont i-md4">品鉴讲堂</span>
	</a>
	 -->
	 
	 <a class="menu<?php if($this->action=='exhibition') echo ' sel';?>" data-role="tab" href="/v-exhibition.html" data-toggle="article">
		<span class="menu-icon iconfont i-md-exhibition">特别展览<?php echo $this->action?></span>
	</a>
</nav>