<?php
	if(!$page_title) $page_title=SITE_NAME;
	$ats_path=FILE_URL.'/assets/';
	$m3d_path=FILE_URL.'/m3d/';
?>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width,initial-scale=1.0, user-scalable=0,minimum-scale=1.0, maximum-scale=1.0">
		<meta name="screen-orientation" content="portrait">
		<meta name="x5-orientation" content="portrait">
		<meta name="msapplication-tap-highlight" content="no">
		<title><?=$page_title?></title>
		<link rel="stylesheet" href="<?=$ats_path?>agile/css/agile.layout.css">
		<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/flat.component.css">
		<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/flat.color.css">
		<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/iconline.css">
<?php
	if(!$this->acl && !$_GET['__DEBUG'])
	{
?>
	<script type="text/javascript">
		var browser={versions:function(){var u=navigator.userAgent,app=navigator.appVersion;return{trident:u.indexOf("Trident")>-1,presto:u.indexOf("Presto")>-1,webKit:u.indexOf("AppleWebKit")>-1,gecko:u.indexOf("Gecko")>-1&&u.indexOf("KHTML")==-1,mobile:!!u.match(/AppleWebKit.*Mobile.*/),ios:!!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),android:u.indexOf("Android")>-1||u.indexOf("Linux")>-1,iPhone:u.indexOf("iPhone")>-1,iPad:u.indexOf("iPad")>-1,webApp:u.indexOf("Safari")==-1,weixin:u.indexOf("MicroMessenger")>-1,qq:u.match(/\sQQ/i)==" qq"}}(),language:(navigator.browserLanguage||navigator.language).toLowerCase()};if(browser.versions.mobile||browser.versions.android||browser.versions.ios){}else{if(window.top.location.pathname!='/pc.html'){location='/pc.html?p='+escape(window.location.href);}}
	</script>
<?php
	}
?>
