<!DOCTYPE html>
<html>
 <head>
  <title>用户管理</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="<?=FILE_URL?>/css/css.css">
 </head>
<body> 

<table width="98%" border=0 align=center cellpadding=2 cellspacing=1 bordercolor="#799AE1" class=tableBorder>
<tbody>
<tr>
<th align=center style="height: 23px">新增管理员</th>
</tr>

	   <tr bgcolor="#DEE5FA">
        <td align="center" class=txlrow> 
  <tbody><tr>
  <td valign="top">
    <form action="/admin-user-add.html" method="post" name="userform" onsubmit=""> 
        <table class="table_area" align="center" cellpadding="3" cellspacing="1" width="98%">
          <tbody>
			<tr class="b" align="left">
            <td width="80">用户名</td>
            <td><input class="box" name="u_n" id="u_n" value="" size="50" type="text"></td>
			</tr>
			<tr class="b" align="left">
            <td width="80">密码</td>
            <td><input class="box" name="u_p" id="u_p" value="" size="50" type="text"></td>
			</tr>
			<tr class="b" align="left">
            <td width="80">角色</td>
            <td>
				  <label>
				  <select id=acl name=acl>
					<OPTION value=-1 selected>请选择</OPTION>
					<?php foreach($this->acls as $k=>$i){?>
						<OPTION value=<?=$i['acl']?> ><?=$i['acl']?></OPTION> 
					<?php }?> 
				  </select>
				  </label>

				  <SCRIPT type=text/javascript> 
						var slt=document.getElementById("acl");
						for(var i=0;i<slt.options.length;i++)
						if(slt.options[i].value=="<?=$_POST['acl']?>")
						slt.options[i].selected=true;
				  </SCRIPT>
			</td>
			</tr>
			<tr class="b" align="left">
            <td width="80">描述</td>
            <td><input class="box" name="desc" id="desc" value="" size="50" type="text"></td>
			</tr>
          <tr class="b" align="left">
            <td colspan="2"><center>
                <input name="submit" class="btn" value="确定" type="submit">
                <input name="reset" class="btn" value="重置" type="reset">
              </center></td>
          </tr>
        </tbody></table>
	    <center> 
	    </center>
    </form>
  </td>
  </tr>
  </tbody>
</td>
      </tr>


<tr bgcolor="#DEE5FA">
<td align=center class=txlrow></td>
</tr>
</tbody></table>

<?php if($this->res1){?>  
<table width="98%" border=0 align=center cellpadding=2 cellspacing=1 bordercolor="#D73A42" class=tableBorder>
<tr>
<th align=center style="height: 23px;background-color:red"><?=$this->res1?></th>
</tr>
</table>
<?php }?>
</body>
</html>