<?php
require_once COMM_PATH .'/lib/jssdk.php';
$jssdk = new JSSDK(WX_APPID,WX_APPSEC);
$signPackage = $jssdk->GetSignPackage();

$i=$this->detail;

// 是否语音
$hasAudio = file_exists(realpath(cm_url::get('yucheng-img-path')).'/m3d/audio/'.$i['id'].'.mp3');

//判断3d 图片是非存在
$m_3d2 = '';
$has3d = false;
if(file_exists(cm_url::get('yucheng-img-path').'/m3d/3dpic/'.$i['id'])) {
    $has3d = true;
    if(trim($i['m_3d'])) {
        $m_3d=trim($i['m_3d']);
    } else {
    	/*
    		rdp	阻力
    		p1	浏览器宽度平铺
    		p2	右下方增加平铺按钮
    		p3	加载时显示遮罩
    		p4	是否显示loading过程
    		p5	是否运行全屏
    	*/
    	$m_3d=<<<AAA
    	  var show3d;
    	  function init1() {
    		var xn = 20;
    		var yn = 9;
    		var xr = true;
    		var yr = true;
    		var xs = 0.05;
    		var ys = 0.03;
    		var x0 = 0;
    		var y0 = 4;
    		var minz = 0.3;
    		var maxz = 1.3;
    		var defz = 1;
    		var rdp = 0.95;
    		var p1 = true;
    		var p2 = false;
    		var p3 = false;
    		var p4 = true;
    		var p5 = false;
    		
    		var p_when = 5;
    		var px1 = 0;
    		var px2 = 0;
    		var py1 = 0;
    		var py2 = 0;
    
    		var r01= 0;
    		var r02= 0;
    		var rtop1=0;
    		var rtop2=0;
    		var qsx1 =0;
    		var qx1 = 0;
    		var qsx2 =0;
    		var qx2 = 0;
    
    		var xr1 = 0;
    		var xr2 = 0;
    		var yr1 = 0;
    		var yr2 = 0;
    
    		var psx1 = 0;
    		var cx1 = 0;
    		var cx01 = 0;
    		var psy1 = 0;
    		var cy1 = 0;
    		var cy01 = 0;
    		var psx2 = 0;
    		var cx2 = 0;
    		var cx02 = 0;
    		var psy2 = 0;
    		var cy2 = 0;
    		var cy02 = 0;
    
    		show3d = new show3d("s3d1","item_i_id",400,600,"#000",xn,yn,xr,yr,xs,ys,x0,y0,minz,maxz,rdp,p1,p2,p3,"jpg",p4,"",p5,defz,p_when,px1,py1,px2,py2,r01,r02,xr1,yr1,xr2,yr2,psx1,cx1,psy1,cy1,psx2,cx2,psy2,cy2,cx01,cy01,cx02,cy02,qsx1,qx1,qsx2,qx2,rtop1,rtop2);
    	  }
    	  window.onload = init1;
AAA;
    }
    $m_3d2=str_replace('item_i_id',FILE_URL.'/m3d/3dpic/'.$i['id'],$m_3d);
}
$page_title=SITE_NAME;
if(!$page_title) $page_title=SITE_NAME;
$ats_path=FILE_URL.'/assets/';
$m3d_path=FILE_URL.'/m3d/';
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width,initial-scale=1.0, user-scalable=0,minimum-scale=1.0, maximum-scale=1.0">
	<meta name="screen-orientation" content="portrait">
	<meta name="x5-orientation" content="portrait">
	<meta name="msapplication-tap-highlight" content="no">
	<title><?=$page_title?></title>
	<link rel="stylesheet" href="<?=$ats_path?>agile/css/agile.layout.css">
	<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/flat.component.css">
	<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/flat.color.css">
	<link rel="stylesheet" href="<?=$ats_path?>agile/css/flat/iconline.css">
	<link rel="stylesheet" href="<?=$m3d_path?>d_1.css?v=<?=CSS_VERSION?>">
	<script type="text/javascript" src="<?=$m3d_path?>s3d/s3d.js?v=5<?=CSS_VERSION?>"></script>
	<script type="text/javascript"><?=$m_3d2?></script>
</head>
<body style="width:100%;-ms-touch-action:none;position:absolute;" class="bdtl">
	<ul class="listitem" style="padding:0px;margin-top:0px">
		<li id="dl4" style="margin:0px;border-radius:0px">
			<span id="spn3"></span>
			<span id="spn1"></span>
			<span id="spn2"></span>
			<span id="spn5" onclick="document.getElementById('alt0').style.display='block'"></span>
		</li>
		<li id="dl3">
			<div id="s3d1"></div>
		</li>
	</ul>
</body>
</html>