<?php
//$page_title=SITE_NAME;
$page_title='馆藏展品';
require_once(global_info::$v_path_client.'/comm/m_head.phtml');
?>
	<link rel="stylesheet" href="<?=$m3d_path?>d_1.css?v=<?=CSS_VERSION?>">
</head>
<body style="width:100%;-ms-touch-action:none;position:absolute;" class="gczp">
	<?php if($this->acl) echo '<form method="post" action="" enctype="multipart/form-data">';?>
	<div class="imx">
		<ul class="listitem wp100">
			<li id="top1"></li>
			<li class="mn1">
				<table>
					<tr>
						<td class="m1" align="center"><div class="mnl" style="background:url(<?=$m3d_path?>images/gc1.jpg) no-repeat;background-size:100%;"></div></td>
						<td class="m2">
							<a href="/v-l-m-1.html">
								<table class="mh1">
									<td class="mtt">明清瓷器</td>
									<td><span>康熙</span></td>
									<td><span>雍正</span></td>
									<td><span>乾隆</span></td>
								</table>
								<div class="mh2">
									明清瓷器是我国瓷器发展史上的极盛时期。彩秞品种丰富多彩，“其彩色，则霁红、矾红、霁青、粉青、冬青、紫绿、金、银、漆黑、杂彩，随意而施。”
								</div>
								<div style="width:100%">
									<div class="xq1"></div>
								</div>
							</a>
						</td>
					<tr>
				</table>
			</li>
			<li class="ln2"></li>
			<li class="mn1">
				<table>
					<tr>
						<td class="m1" align="center"><div class="mnl" style="background:url(<?=$m3d_path?>images/gc2.jpg) no-repeat;background-size:100%;"></div></td>
						<td class="m2">
							<a href="/v-l-m-2.html">
								<table class="mh1">
									<td class="mtt">宋元瓷器</td>
									<td><span>汝</span></td>
									<td><span>官</span></td>
									<td><span>哥</span></td>
									<td><span>定</span></td>
									<td><span>钧</span></td>
								</table>
								<div class="mh2">
									宋元时期，精益求精的官窑工艺绝伦，注重实用的民窑简朴大方，融合异国风格的外销瓷特征，三者交相辉映，异彩纷呈，共同构成了宋元瓷器的灿烂文化。
								</div>
								<div style="width:100%">
									<div class="xq1"></div>
								</div>
							</a>
						</td>
					<tr>
				</table>
			</li>
			<li class="ln2" style="border:none"></li>
		</ul>
		<ul class="bsy">
			<!-- 一周一珍 -->
			<li>
				<table class="y1">
					<tr class="tp"><td class="lt"></td><td class="ce"></td><td class="rt"></td></tr>
					<tr class="mi">
						<td class="lt"></td><td class="ce" id="sw1">
							<div class="swd">
								<a class="dr1" href="/v-l-t-z.html?forwxsbug2">&nbsp;</a>
							</div>
							<div class="tzq">
								<?php foreach($this->l as $k=>$i){?>
								<a href="/v-d-i-<?=$i['id']?>.html">
								<?php if(preg_match('/^\/m3d\//', $i['img_name'])): ?>
								<div style="background:url('<?=FILE_URL.$i['img_name']?>') no-repeat center;background-size:auto 100%;"></div>
								<?php else: ?>
								<div style="background:url(<?=M_PIC_URL.'/'.$i['id'].'/s/'.$i['img_name']?>) no-repeat center;background-size:auto 100%;"></div>
								<?php endif; ?>
								<?=$i['name']?>
								</a>
								<?php }?>
							</div>
						</td><td class="rt"></td>
					</tr>
					<tr class="bn"><td class="lt"></td><td class="ce"></td><td class="rt"></td></tr>
				</table>
			</li>
			<li class="ln2" style="border:none"></li>
		</ul>
		<?php require_once(global_info::$v_path_client.'/comm/m_foot.phtml');?>
	</div>
	<?php if($this->acl) echo '</form>';?>
</body>
</html>
<script type="text/javascript">
	window.onload=function(){
		var i=document.getElementById("top1");
		cw1(i,600,230);
		gbc("mnl",210,248);
	}
</script>
<?php require_once(global_info::$v_path_client.'/comm/b_foot.phtml');?>